name: Build R Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install Dependencies
        run: Rscript -e "install.packages(c('devtools', 'remotes'))"

      - name: Build R Package (Linux/Mac)
        if: matrix.os != 'windows-latest'
        run: |
          R CMD build .

      - name: Build R Package (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          R CMD build --binary .

      - name: Upload Package Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: r-packages
          path: "*.tar.gz, *.zip, *.tgz"

      - name: Move Packages to Repository
        run: |
          mkdir -p packages
          mv *.tar.gz *.zip *.tgz packages/ 2>/dev/null || true

      - name: Test Package Installation
        run: |
          Rscript -e '
          # Set repository to local packages directory
          pkgs <- jsonlite::fromJSON("packages.json")$package
          
          # Try to install each package from local files
          results <- lapply(pkgs, function(pkg) {
            pkg_file <- list.files("packages", pattern = paste0(pkg, "_.*\\.(tar\\.gz|zip|tgz)$"), full.names = TRUE)[1]
            if(is.na(pkg_file)) {
              return(sprintf("Package file not found for %s", pkg))
            }
            
            tryCatch({
              install.packages(pkg_file, repos = NULL, type = "source")
              sprintf("Successfully installed %s", pkg)
            }, error = function(e) {
              sprintf("Failed to install %s: %s", pkg, e$message)
            })
          })
          
          # Print results
          cat(unlist(results), sep = "\n")
          
          # Check if any installations failed
          if(any(grepl("Failed|not found", unlist(results)))) {
            quit(status = 1)
          }
          '

      - name: Update packages.json
        run: |
          # Your existing packages.json update script
          