name: Build R Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install Dependencies
        run: Rscript -e "install.packages(c('devtools', 'remotes'))"

      - name: Build R Package (Linux/Mac)
        if: matrix.os != 'windows-latest'
        run: |
          R CMD build .

      - name: Build R Package (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          R CMD build --binary .

      - name: Upload Package Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: r-packages
          path: "*.tar.gz, *.zip, *.tgz"

      - name: Move Packages to Repository
        run: |
          mkdir -p packages
          mv *.tar.gz *.zip *.tgz packages/ 2>/dev/null || true          